---
- name: Create Multiple Users
  hosts: all
  become: yes
  vars:
    users:
      - name: alice
        shell: /bin/bash
      - name: bob
        shell: /bin/bash
  tasks:
    - name: Add users
      user:
        name: "{{ item.name }}"
        shell: "{{ item.shell }}"
        state: present
      with_items: "{{ users }}"
